/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author usuario
 */
public class TipoVehiculoRetirar extends javax.swing.JFrame {

    /**
     * Creates new form TipoVehiculo
     */
    public TipoVehiculoRetirar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aCoche = new javax.swing.JButton();
        aCamion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        borde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccionar tipo");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aCoche.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        aCoche.setText("COCHE");
        aCoche.setBorder(null);
        aCoche.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCocheActionPerformed(evt);
            }
        });
        getContentPane().add(aCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 323, 143));

        aCamion.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        aCamion.setText("CAMION");
        aCamion.setBorder(null);
        aCamion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCamionActionPerformed(evt);
            }
        });
        getContentPane().add(aCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 323, 143));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SELECCIONE EL TIPO DE VEHICULO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 326, 44));

        volver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 443, 117, 40));

        borde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondotipo.jpg"))); // NOI18N
        borde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void aCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCocheActionPerformed
        this.setVisible(false);
        VerListasCoches aCoche = new VerListasCoches();
        aCoche.setVisible(true);
    }//GEN-LAST:event_aCocheActionPerformed

    private void aCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCamionActionPerformed
        this.setVisible(false);
        VerCamiones aCamion = new VerCamiones();
        aCamion.setVisible(true);
    }//GEN-LAST:event_aCamionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aCamion;
    private javax.swing.JButton aCoche;
    private javax.swing.JLabel borde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
