
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author usuario
 */
public class TipoVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form TipoVehiculo
     */
    public TipoVehiculo() {
        initComponents();
        llenarPlazasDisponibles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aCoche = new javax.swing.JButton();
        aCamion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        plazasdisponibles = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        borde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dar de alta");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aCoche.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        aCoche.setText("COCHE");
        aCoche.setBorder(null);
        aCoche.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCocheActionPerformed(evt);
            }
        });
        getContentPane().add(aCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 323, 143));

        aCamion.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        aCamion.setText("CAMION");
        aCamion.setBorder(null);
        aCamion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aCamionActionPerformed(evt);
            }
        });
        getContentPane().add(aCamion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 323, 143));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SELECCIONE EL TIPO DE VEHICULO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 380, 30));

        volver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 117, 40));

        plazasdisponibles.setEditable(false);
        getContentPane().add(plazasdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PLAZAS DISPONIBLES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 160, 40));

        borde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondotipo.jpg"))); // NOI18N
        borde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        Principal principal = new Principal();
        principal.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void aCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCocheActionPerformed
        Aparcamiento parking = leerBaseDatos();
        if (parking.contador > 0) {
            this.setVisible(false);
            LlenarDatosCoche aCoche = new LlenarDatosCoche();
            aCoche.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay sitio en el aparcamiento");
        }
    }//GEN-LAST:event_aCocheActionPerformed

    private void aCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aCamionActionPerformed
        Aparcamiento parking = leerBaseDatos();
        if (parking.contador > 0) {
            this.setVisible(false);
            LlenarDatosCamion aCamion = new LlenarDatosCamion();
            aCamion.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay sitio en el aparcamiento");
        }
    }//GEN-LAST:event_aCamionActionPerformed
    private Aparcamiento leerBaseDatos() {
        Aparcamiento parking = null;
        FileInputStream fisPer = null;
        try {
            fisPer = new FileInputStream("misdatos.dat");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TipoVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ObjectInputStream guardar1 = new ObjectInputStream(fisPer);
            parking = (Aparcamiento) guardar1.readObject();
            guardar1.close();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(TipoVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        return parking;

    }

    public void llenarPlazasDisponibles() {
        Aparcamiento parking = leerBaseDatos();
        plazasdisponibles.setText(String.valueOf(parking.contador));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aCamion;
    private javax.swing.JButton aCoche;
    private javax.swing.JLabel borde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField plazasdisponibles;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
