
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VerCamiones extends javax.swing.JFrame {

    /**
     * Creates new form VerCamiones
     */
    public VerCamiones() {
        initComponents();
        iniciartabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCamiones = new javax.swing.JTable();
        botonbuscarespecifico = new javax.swing.JButton();
        buscarpormatricula = new javax.swing.JTextField();
        botonactualizartodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        retirarcoche = new javax.swing.JButton();
        borde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retirar camion");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaCamiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCamiones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 155, 599, 325));

        botonbuscarespecifico.setText("BUSCAR ESPECIFICO");
        botonbuscarespecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarespecificoActionPerformed(evt);
            }
        });
        getContentPane().add(botonbuscarespecifico, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 86, 200, 38));

        buscarpormatricula.setText("Introduzca matricula..");
        buscarpormatricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarpormatriculaMouseClicked(evt);
            }
        });
        buscarpormatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarpormatriculaKeyPressed(evt);
            }
        });
        getContentPane().add(buscarpormatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 89, 200, 33));

        botonactualizartodo.setText("ACTUALIZAR TODO");
        botonactualizartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonactualizartodoActionPerformed(evt);
            }
        });
        getContentPane().add(botonactualizartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 86, 154, 38));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" -------- = Disponible desde  coches");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 280, 39));

        volver.setText("VOLVER");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, -1, -1));

        retirarcoche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        retirarcoche.setText("RETIRAR SELECCIONADO");
        retirarcoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarcocheActionPerformed(evt);
            }
        });
        getContentPane().add(retirarcoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 491, 170, -1));

        borde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoretirar.jpg"))); // NOI18N
        borde.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarpormatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarpormatriculaMouseClicked
        buscarpormatricula.setText("");
    }//GEN-LAST:event_buscarpormatriculaMouseClicked

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.setVisible(false);
        TipoVehiculoRetirar tipo = new TipoVehiculoRetirar();
        tipo.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void botonactualizartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonactualizartodoActionPerformed
        iniciartabla();
    }//GEN-LAST:event_botonactualizartodoActionPerformed

    private void botonbuscarespecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarespecificoActionPerformed
        Aparcamiento parking = leerBaseDatos();
        iniciartabla();// Si vuelvo a buscar reinicio todo para empezar
        int y = 0;
        GregorianCalendar actual = new GregorianCalendar();
        if (!buscarpormatricula.getText().isEmpty() && !buscarpormatricula.getText().equals("Introduce matricula...") && !buscarpormatricula.getText().equals("--------")) {
            String valor = buscarpormatricula.getText().toUpperCase();
            buscarpormatricula.setText(valor);
            for (int x = 0; x < parking.parking.size(); x++) {
                if (tablaCamiones.getValueAt(x, 0).equals(valor)) {
                    cambiarModeloTabla(1);
                    tablaCamiones.setValueAt(parking.parking.get(valor).getMatricula(), 0, 0);
                    tablaCamiones.setValueAt(parking.parking.get(valor).siono(), 0, 1);
                    int valor1 = (int) parking.parking.get(valor).anchoOruedas();
                    tablaCamiones.setValueAt(valor1, 0, 2);
                    tablaCamiones.setValueAt(parking.parking.get(valor).getFecha(), y, 3);
                    long minutos = (actual.getTimeInMillis() - parking.parking.get(valor).getMinutos()) / (60 * 1000);
                    tablaCamiones.setValueAt(String.valueOf(minutos), y, 4);

                    y++;
                    break;
                }
                if (x == parking.parking.size() - 1 && y == 0) {
                    JOptionPane.showMessageDialog(this, "Ningun valor encontrado para matricula especificada");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Introduce matricula");
        }
    }//GEN-LAST:event_botonbuscarespecificoActionPerformed

    private void retirarcocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarcocheActionPerformed
        if (tablaCamiones.getSelectedRowCount() == 1) { // Para que no haga nada sino se ha seleccionado ninguno o mas de uno
            Aparcamiento parking = leerBaseDatos();
            if (tablaCamiones.getRowCount() > 1) { // Si estamos viendo todos 
                String valor = tablaCamiones.getValueAt(tablaCamiones.getSelectedRow(), 0).toString(); // En la columna cero estan las matriculas. Guardamos valor de llave de fila seleccionada
                String parking1[] = new String[parking.parking.size()];
                int x = 1;
                while (x == 1) {
                    x = 0;
                    for (String key : parking.parking.keySet()) { // Obtengo todas las llaves y las almaceno en un vector
                        parking1[x] = (key);
                        x++;
                    }
                } //Luego las comparo con la guardada en variable valor
                for (int i = 0; i < parking.parking.size(); i++) {
                    if (parking.parking.get(parking1[i]).getMatricula().equals(valor)) {
                        Vehiculo v = parking.parking.get(parking1[i]);// Para obtener factura
                        crearFactura(v);// Creamos mediante metodo creado con el objeto retirado
                        String total = parking.sacarVehículo(valor);
                        JOptionPane.showMessageDialog(this, "Vehiculo retirado " + total);
                        JOptionPane.showMessageDialog(this, "Factura creada en carpeta de proyecto");
                        guardarBaseDatos(parking);
                        iniciartabla();//Actualizo la ventana
                    }
                }
            } else {//Si estamos viendo 1 especifico
                String valor = tablaCamiones.getValueAt(tablaCamiones.getSelectedRow(), 0).toString();
                String parking1[] = new String[1];
                Vehiculo v = parking.parking.get(valor);// Para obtener factura
                crearFactura(v);// Creamos mediante metodo creado con el objeto retirado
                String total = parking.sacarVehículo(valor);
                JOptionPane.showMessageDialog(this, "Vehiculo retirado " + total);
                JOptionPane.showMessageDialog(this, "Factura creada en carpeta de proyecto");
                guardarBaseDatos(parking);
                iniciartabla();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione UN vehiculo a retirar");
        }
    }//GEN-LAST:event_retirarcocheActionPerformed

    private void buscarpormatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarpormatriculaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botonbuscarespecificoActionPerformed(null);
        }
    }//GEN-LAST:event_buscarpormatriculaKeyPressed

    /**
     * @param args the command line arguments
     */
    private void iniciartabla() {
        Aparcamiento parking = leerBaseDatos();
        Aparcamiento aparcamiento = leerBaseDatos();
        String parking1[] = new String[aparcamiento.parking.size()];
        int x = 1;
        while (x == 1) {
            x = 0;
            for (String key : aparcamiento.parking.keySet()) { // Obtengo todas las llaves y las almaceno en un vector
                parking1[x] = (key);
                x++;
            }
        }
        cambiarModeloTabla(parking.parking.size());
        GregorianCalendar actual = new GregorianCalendar();// Para obtener la fecha del momento
        for (int y = 0; y < aparcamiento.parking.size(); y++) {
            if (aparcamiento.parking.get(parking1[y]).getIdentificador() == 1) {// Si es uno significa que es camion

                tablaCamiones.setValueAt(aparcamiento.parking.get(parking1[y]).getMatricula(), y, 0);
                tablaCamiones.setValueAt(aparcamiento.parking.get(parking1[y]).siono(), y, 1);
                int entero = (int) aparcamiento.parking.get(parking1[y]).anchoOruedas();
                tablaCamiones.setValueAt(entero, y, 2);
                tablaCamiones.setValueAt(aparcamiento.parking.get(parking1[y]).getFecha(), y, 3);
                long minutos = (actual.getTimeInMillis() - aparcamiento.parking.get(parking1[y]).getMinutos()) / (60 * 1000);
                tablaCamiones.setValueAt(String.valueOf(minutos), y, 4);
            } else {
                tablaCamiones.setValueAt("", y, 0);
                tablaCamiones.setValueAt("", y, 1);
                tablaCamiones.setValueAt("", y, 2);
                tablaCamiones.setValueAt("", y, 3);
                tablaCamiones.setValueAt("", y, 4);

            }

        }

        for (int y = 0; y < aparcamiento.parking.size(); y++) {
            if (tablaCamiones.getValueAt(y, 0).equals("") && tablaCamiones.getValueAt(y, 1).equals("") && tablaCamiones.getValueAt(y, 2).equals("") && tablaCamiones.getValueAt(y, 3).equals("")) {
                tablaCamiones.setValueAt("--------", y, 0);
                tablaCamiones.setValueAt("--------", y, 1);
                tablaCamiones.setValueAt("--------", y, 2);
                tablaCamiones.setValueAt("--------", y, 3);
                tablaCamiones.setValueAt("--------", y, 4);

            }
        }

    }

    private void cambiarModeloTabla(int tamañoTabla) {
        DefaultTableModel md = new DefaultTableModel();
        Object[] fila1 = {"Matricula", "Descuento", "Nº de Ruedas", "Fecha de entrada", "Minutos Totales"};
        md.setRowCount(tamañoTabla);
        md.setColumnCount(5);
        md.setColumnIdentifiers(fila1);
        tablaCamiones.setModel(md);
    }

    private Aparcamiento leerBaseDatos() {
        Aparcamiento parking = null;
        FileInputStream fisPer = null;
        try {
            fisPer = new FileInputStream("misdatos.dat");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VerCamiones.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ObjectInputStream oisPer = new ObjectInputStream(fisPer);
            try {
                parking = (Aparcamiento) oisPer.readObject();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VerCamiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(VerCamiones.class.getName()).log(Level.SEVERE, null, ex);
        }
        return parking;
    }

    private void guardarBaseDatos(Aparcamiento parking) {
        FileOutputStream guardar = null;
        try {
            guardar = new FileOutputStream("misdatos.dat");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LlenarDatosCamion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ObjectOutputStream guardar1 = new ObjectOutputStream(guardar);
            guardar1.writeObject(parking);
            guardar1.close();
        } catch (IOException ex) {
            Logger.getLogger(LlenarDatosCamion.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void crearFactura(Vehiculo v) {
        String introduccion = "FACTURA VEHICULO RETIRADO";
        String matricula = "NUMERO DE MATRICULA: " + v.getMatricula();
        String identificador = "";
        if (v.getIdentificador() == 0) {
            identificador = "TIPO DE VEHICULO: Coche";
        } else {
            identificador = "TIPO DE VEHICULO: Camión";
        }
        String fechaEntrada = "FECHA Y HORA DE ENTRADA: " + v.getFecha();
        GregorianCalendar fsalida = new GregorianCalendar();
        Date fecha1 = fsalida.getTime();
        String fechaSalida = "FECHA Y HORA DE SALIDA: " + fecha1.toLocaleString();
        long minutos = (fsalida.getTimeInMillis() - v.getMinutos()) / (60 * 1000);
        String minutos1 = "MINUTOS TRANSCURRIDOS DESDE ENTRADA: " + minutos;
        String descuento = "DESCUENTO POR ABONO(40%): " + v.siono();
        double importeTotal = v.calcularImporte(minutos);
        String importeTotal1 = "IMPORTE TOTAL A PAGAR: " + importeTotal+" euros";
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String nombreFactura = v.getMatricula() + " " + dateFormat.format(fecha1);
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(nombreFactura + ".txt"));
            bw.write(introduccion);
            bw.newLine();
            bw.write(matricula);
            bw.newLine();
            bw.write(identificador);
            bw.newLine();
            bw.write(fechaEntrada);
            bw.newLine();
            bw.write(fechaSalida);
            bw.newLine();
            bw.write(minutos1);
            bw.newLine();
            bw.write(descuento);
            bw.newLine();
            bw.write(importeTotal1);
            bw.flush();
            //Cerramos el stream
            bw.close();
        } catch (IOException ioe) {
            System.out.println("Error IO: " + ioe.toString());
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCamiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel borde;
    private javax.swing.JButton botonactualizartodo;
    private javax.swing.JButton botonbuscarespecifico;
    private javax.swing.JTextField buscarpormatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retirarcoche;
    private javax.swing.JTable tablaCamiones;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
